### ISSUE TITLE
Deploy contract to mainnet

### ISSUE THREAD

**Issue by hollygrimm** [PrisonArt/restore#12]

**Comment by andytudhope** [comment]
https://etherscan.io/address/0x136fA646d6eEB201D4424c0c6a8d6cD806fEB96f#code RESTORE

https://etherscan.io/address/0x864c54FB4bC795140E8c48e3f7372A9DF01B1f1F#code JUSTICE

https://etherscan.io/tx/0x8273f0a487c9d34f403454602848c8ce6632b2c44fa3df75d1d108a9f2148101 GENESIS

---

https://etherscan.io/tx/0x9df6288567880a2c5480772f281dcf2e6d8c5b3ba5fdf40830723d4775093a3d - Royalties set to PA payment address in perpetuity. We receive royalties here for regulatory clarity, and then disburse to artists. It must also be this way due to our use of contract wide royalties.
